services:
  - type: web
    name: gyanodaya-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: /api/v1
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: SWAGGER_ENABLED
        value: "true"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE_MB
        value: "5"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
